baseurl:
url: https://chauby.github.io
title: Newflash pro
subtitle: "专业设计研发及生产手机周边配件"
description: "Chauby's personal page"
date_format: "ordinal"
# timezone: Asia/Chengdu
encoding: "utf-8"
side_bar_repo_limit: 5

author: Chauby
organization: 深圳市金果力有限公司
# organization_url: http://www.uestc.edu.cn
github_username: 0755-85221676/15279558188
location: Shenzhen, China
email: admin@ikinple.com

# Navigation
navs:
  -
    href: /
    label: 主页

  -
    href: /cv/
    label: 产品

  -
    href: /publications/
    label: 联系我们

  -
    href: /categories/
    label: 博客

  -
    href: /wiki/
    label: Wiki

  # -
  #   href: /links/
  #   label: Links

# RSS
subscribe_rss: /feed.xml

# Jekyll
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chauby/chauby.github.io

# Search
simple_jekyll_search:
    fulltext: false # full text search enable
    limit: 10 # limitation of the search results to show

# Analytics
google:
    analytics_id: UA-80669434-1
github: [metadata]
